project:
  type: book

lang: es

book:
  title: Not used
  author: Not used
  #date: "10/4/2022"
  chapters:
    - index.qmd
    # - Bit1.qmd
    # - Bit2.qmd
    # - Bit3.qmd
    # - Bit4.qmd
    # - Anteproyecto.qmd
    - Proyecto.qmd
    - references.qmd
    - Anexo.qmd

bibliography: references.bib
csl: apa.csl
format:
  html:
    theme: cosmo
  pdf:
    mainfont: "Calibri"
    fontsize: 11pt
    documentclass: report
    classoption: ["onepage", "openany"]
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: true
    lof: true
    lot: true
    #fig-pos: 'H'
    fig-width: 4.8
    fig-height: 3
    fig-format: pdf	
    number-sections: false


editor: source

geometry:
  - left=.75in
  - right=.75in
  - top=.75in
  - bottom=.75in
  - textwidth=4.5in
  - marginparsep=.25in
  - marginparwidth=2.25in
  
from: markdown+tex_math_single_backslash
