# Introducción al marco teórico

En términos generales, la demografía es "es una ciencia que estudia las poblaciones humanas, su dimensión, estructura, evolución y características generales" [@bruno2019analisis] y además "estudia estadísticamente la estructura y la dinámica de las poblaciones, así como los procesos concretos que determinan su formación, conservación y desaparición [...] tales procesos son los de fecundidad, mortalidad y migración: emigración e inmigración"  [@bruno2019analisis]. De acuerdo al mismo autor, hay dos grandes tipos de demografía: la estática, que "estudia las poblaciones humanas en un momento de tiempo determinado desde un punto de vista de dimensión, territorio, estructura y características estructurales" [-@bruno2019analisis] y la dinámica, "que estudia las poblaciones humanas desde el punto de vista de la evolución en el transcurso del tiempo y los mecanismos por los que se modifica la dimensión, estructura y distribución geográfica de las poblaciones" [-@bruno2019analisis]. Bajo estas concepciones, el presente trabajo caería en el campo de la demografía dinámica, pues se buscará realizar pronóstico sobre la serie histórica de defunciones de Costa Rica de 1950 a 2020. En ese sentido, @REES2020239 afirma que una de las mayores contribuciones de la demografía ha sido el desarrollo de modelos para la proyección de futuras poblaciones, lo cuál está estrechamente relacionado con la proyección de defunciones. Según @maccio1985diccionario la mortalidad o defunción se emplea para expresar la acción de la muerte sobre la población y esta se mide en valores absolutos y sobre el año calendario. Por su parte y de acuerdo a @brownlee, la realización de predicciones sobre el futuro se denomina extrapolación en el tratamiento estadístico clásico de los datos de las series temporales. Los campos más modernos que se centran en el tema, lo denominan pronóstico de series temporales. El pronóstico consiste en tomar modelos ajustados a datos históricos y utilizarlos para predecir observaciones futuras. Asimismo, una serie cronológica o crónica se le llama a "la que forman los valores sucesivos que una cierta variable ha tomado en el transcurso del tiempo" [@maccio1985diccionario], como lo puede ser, por ejemplo, la serie de defunciones totales anuales para un país en específico.


Ahora bien, las teorías demográficas "pretenden explicar los patrones del crecimiento de la población en diversos países del mundo dando cuenta de la estructura y la dinámica de la población y estableciendo leyes o principios que regirían esos fenómenos" [@bruno2019analisis]. Más específicamente, una teoría demográfica "explicaría los cambios y acontecimientos de las poblaciones humanas, de su dimensión, estructura, evolución y características generales, tanto desde un punto de vista cuantitativo (estadístico) como cualitativo (biológico, sociológico, cultural y económico)" [@bruno2019analisis].

La primer teoría global de la población, y una de las más famosas, es la malthusiana, enunciada por Thomas Robert Malthus en 1978 en su Ensayo sobre el principio de población, que consistió  "en una teoría donde se establece una ley general que explica el crecimiento total de la población en relación con otra variable fuera del contexto social, como lo es la disponibilidad de alimentos" [@sarrible2009teoria]. A su vez, explica que la teoría malthusiana porpone que "el ritmo de crecimiento de la población responde a una progresión geométrica, mientras que el ritmo de aumento de los recursos para su supervivencia lo hace en progresión aritmética" [@bruno2019analisis]. De esta manera, Malthus sostenía que el hambre, la guerra y otras catástrofes impedían que ocurriera la pauperización grafual de la especie humana, pues mantenían controlado el número de nacimientos [@bruno2019analisis]. @sarrible2009teoria cuestiona la vigencia de esta teoría aludiendo que "hay países que crecen y otros que tieden a la población estacionariao tieneen crecimiento natural negativo [...] hay países que creen, a pesar de que el saldo migratorio les sea desfavorable y otroq ue crecen gracias a las migraciones internacionales" [-@sarrible2009teoria] 

De acuerdo a @mariscal2018tres, una de las teorías demográficas más importantes es la Teoría de la Transición Demográfica (TTD). Esta consiste en una generalización empírica en función de observaciones pasadas y establece una conexión entre la evolución demográfica de la población y el crecimiento económico [@mariscal2018tres]. Por su parte, @alcalde2010teoria define el régimen 
En síntesis, la TTE bajo su estudio establece que las enfermedades degenerativas modernas y las patologías creadas por el ser humano son las principales causas de mortalidad y morbilidad. Como causas secundarias, son aquellas ligadas a hambrunas, pandemias, guerras, originando acusados picos de mortalidad durante la evolución demográfica de las sociedades. Se define el régimen demográfico como "el comportamiento de una población a partir de la evolución de
sus tasas de natalidad, mortalidad y el crecimiento natural o vegetativo, es decir, la diferencia entre el número de nacidos y fallecidos" [-@alcalde2010teoria] y menciona que su propósito es "es explicar
los cambios que se producen en la evolución de la población mundial" [-@alcalde2010teoria].

El mismo autor explica que bajo el régimen demográfico, la TTD da pie a los modelos demográficos más importantes y esta "se produce cuando la natalidad y la mortalidad, o por lo menos uno de los dos fenómenos, ha dejado sus elevados niveles tradicionales para dirigirse hacia porcentajes más bajos, asociados a la fecundidad dirigida y al uso de métodos de lucha contra la natalidad, pasando de una demografía antigua y tradicional a otra moderna" [@alcalde2010teoria]. Elaborada durante los años 30, la TTD "ha sido profundamente revisada, debatida y criticada, pero la mayoría de los especialistas [...]  la consideran
útil y válida didáctica y metodológicamente [...] para analizar el distinto ritmo de crecimiento de la población a lo largo del tiempo o las diferencias existentes en la actualidad entre unos países y
otros de la Tierra. Un punto muy importante para el presente trabajo es que la TTD "se cumple más fielmente en las sociedades industrializadas europeas al producirse el cambio de la dinámica demográfica a raíz de la Revolución industrial, mientras se duda de si es aplicable o no a los países del Tercer Mundo" [@alcalde2010teoria]. Prueba de este punto es que se han propuesto modelos distintos bajo la TTD para países desarrollados y para países subdesarrollados, donde se habla de "revolución demográfica" en los primeros, en alución al crecimiento repentino de la población debido a los factores mortalidad y natalidad, pero de "explosión demográfica" en el caso de los segundos [@alcalde2010teoria]. Entre las razones para el nombre para los países subdesarrollados están que estos, entre 1950 y 1975 alcanzan su transición demográfica como del descenso de la mortalidad gracias a la difusión de los progresos sanitarios [@alcalde2010teoria]. 

Este último punto parece aplicar al caso costarricense, según lo expone @rosero2004situacion, quien afirma que "los logros en los primeros cincuenta años de salud pública en el país (de 1930 a 1980) se alcanzaron mediante el control de enfermedades transmisibles como las diarreicas, la malaria y la tuberculosis [...] estos tres grupos de causas de muerte explican por sí solos la mitad de la disminución de la mortalidad
de 1930 a 1960" [-@rosero2004situacion]

La Teoría de la transición epidemiológica (TTE) surge como alternativa teórica de la ya menciona Teoría de transición demográfica (TTD) debido a la naturaleza descriptiva o evolucionista de esta. La TTE tiene un carácter más multidisciplinar y con esto multifactorial.

Esta teoría establece que los principales factores causantes de las transiciones demográficas son los
factores ecobiológicos de la mortalidad, factores biopsicológicos, como el uso de contraconceptivos ante el aumento de la supervivencia infantil generando un aumento de la EV, factores médicos y de salud pública, factores psicológicos o emocionales, y factores socioeconómicos, ya que los desarrollos económicos establecen los primeros sistemas sanitarios, ayudando así al descenso de la mortalidad y la reducción de la incidencia de las enfermedades infecciosas.

Es importante mencionar que tal como lo establece @mariscal2018tres la TTE, tiene como objeto de estudio la mortalidad, ya que se centra en aspectos como: patrones de enfermedad, causas de las muertes y la interacción de estas con patrones demográficos, económicos y sociológicos.





# Modelos estadísticos propuestos


Con la finalidad de realizar un pronóstico de la serie de defunciones totales anuales de Costa Rica, se desea implementar el modelo estadístico que mejor se ajuste a los datos.

Para nuestro estudio en cuestión, se ha optado por realizar una implementación de Modelos de Espacio-Estado.Particularmente, 
 Modelos Dinámicos Lineales (DLM). 

Tal como lo establece @petrisDLM, estos últimos son una clase de Modelos de Espacio-Estado también llamados Modelos de Espacio-Estado Lineales Gaussianos. Estos modelos son especificados mediante dos ecuaciones, para $t \geq 1$ se tiene:

$$ Y_{t}= F_{t} \theta_{t} + v_{t} , $$
$$  \theta_{t}= G_{t} \theta_{t-1} + w_{t}   $$

$$   (\theta_{0}|D_{0}) \sim \mathcal{N}(m_{0},C_{0})    $$

Donde la primer ecuación es llamada ecuación de observación,la segunda ecuación estado o ecuación del sistema y la última información inicial. 

Es importante señalar que $F_{t}$ y $G_{t}$ son matrices y $(v_{t})$ , $(w_{t})$ son secuencias de ruidos blancos independientes tales que:

$$ v_{t} \sim \mathcal{N}_{m}(0,V_{t}) , $$
$$  w_{t} \sim \mathcal{N}_{p}(0,W_{t})  $$

Los DLM poseen dos supuestos, la linealidad y el supuesto de distribuciones Gaussianas. @petrisDLM señala que este último supuesto puede ser justificado mediante argumentos del teorema del límite central.


La estimación y pronóstico se pueden resolver calculando las distribuciones condicionales de las cantidades de interés, dada la información disponible. Para estimar el vector de estados es necesario computar la densidad condicional $p(\theta_{t} |y_{1}, .., y_{t})$. En particular, nos interesa el problema de filtrado (cuando $s=t$), donde los datos se supone que llegan secuencialmente en el tiempo.

En general, el problema de pronóstico de $k$-pasos hacia adelante consiste en estimar la evolución del sistema $\theta_{t+k}$ para $k \geq 1$ y realizar un pronóstico de $k$-pasos para $Y_{t+k}$.

Según @petrisDLM en los DLM, el filtro de Kalman proporciona las fórmulas para actualizar nuestra inferencia actual sobre el vector de estado conforme se disponga de nuevos datos. 

Para un DLM, si se cumple que:

$$ \theta_{t} | \mathcal{D}_{t} \sim \mathcal{N}(m_{t}, C_{t}) , t \geq 1 $$

Se tiene que:

La densidad de predicción de estado de $k$-pasos con  $k \geq 1$ hacia adelante de $\theta_{t+k}$ dada  la información pasada $D_{t}$ es Gaussiana  con media y varianza condicional dadas respectivamente por:

$$  a_{t}(k) = {E}[\theta_{t+k}|D_{t} ] = G_{t+k}a_{t, k-1}  $$
$$ R_{t}(k)= {Var}[\theta_{t+k}|D_{t} ] =G_{t+k}R_{t,k-1}G^{'}_{t+k} + W_{t+k} $$

La densidad de predicción de $k$-pasos con  $k \geq 1$ hacia adelante de $Y_{t+k}$ dada  la información pasada $D_{t}$, es Gaussiana  con media y varianza condicional dadas respectivamente por:

$$  f_{t}(k) = {E}[Y_{t+k}|D_{t} ] =F_{t+k}a_{t}(k) $$
$$ Q_{t}(k)= {Var}[Y_{t+k}|D_{t} ]  =F_{t+k}R_{t}(k)F^{'}_{t+k} + V_{t+k} $$


## Justificación modelos DLM propuestos


Como se mencionó en @fig-defunciones_ano, la cantidad de defunciones totales siguen una cierta tendencia lineal creciente, en particular para años posteriores a 1980.

Debido a que esta es nuestra variable de interés para realizar un pronóstico, es propicio para nuestro estudio en cuestión la implementación de un modelo con supuesto de linealidad, como se mencionó justamente los DLM siguen este supuesto.

Para llevar a cabo los pronósticos se proponen por tanto tres métodos estadísticos pertenecientes a los DLM, estos son: modelo DLM polinomial de primer orden, modelo DLM polinomial de segundo orden y el modelo ARIMA$(p ,d,q)$.


## Modelo ARIMA$(p ,d,q)$

Como una primer implementación se utiliza un modelo ARIMA$(p ,d,q)$. Tal como lo menciona @petrisDLM un modelo ARIMA$(p ,d,q)$ puede ser considerado un DLM, esto ya que es posible representar todo modelo ARIMA($p$,$d$,$q$) (ya sea univariado o multivariado) como un DLM. 

La escogencia de este modelo al ser un DLM, sigue la misma línea de justificación antes mencionado sobre la elección de modelos DLM para nuestro estudio, siendo este un caso particular de estos.

Sin embargo, es importante mencionar que la escogencia de este modelo como primera implementación también se basa en su simplicidad, y en que dada la bibliografía consultada, se observa que en múltiples investigaciones con temáticas relacionadas a nuestro estudio como el de  @adekambi  y el estudio por @ordorika, se implementa este tipo de modelo.


Tal como lo establece  @petrisDLM entre los modelos más utilizados para el análisis de series temporales se encuentra la clase de modelos de media móvil autorregresiva (ARMA). Para enteros, no negativos $p$ y $q$, un modelo ARMA$(p,q)$ es definido mediante la notación:

$$ Y_{t} = \mu + \sum_{j=1}^{p}\phi_{j}(Y_{t-j} - \mu ) +  \sum_{j=1}^{p}\psi_{j}\epsilon_{t-j} + \epsilon_{t} $$

Donde $(\epsilon_{t})$ es una ruido blanco Gaussiano con varianza $\sigma_{\epsilon}^{2}$ y los parámetros 
 $\phi_{1}, \phi_{2}, ..., \phi_{p}$  satisfacen la condición de estacionariedad.

Cuando los datos no presentan estacionariedad, se suele tomar las diferencias hasta que se obtenga esta, una vez obtenida se procede a ajustar el modelo ARMA$(p,q)$ a la data diferenciada.

Un modelo para un proceso cuya $d$-ésima diferencia sigue un modelo ARMA$(p,q)$ es llamado un ARIMA$(p ,d,q)$.  

La escogencia de los ordenes $p$ y $q$ pueden ser escogidos de una manera informal, observando la autocorrelación empírica y la autocorrelación parcial, o utilizando un criterio de selección de modelos más formal como lo es el AIC y BIC.


## Modelos polinomiales de primer y segundo orden


Se propone un modelo DLM de primer orden ya que como establece @optimalDLM los DLM de primer orden son algoritmos recomendados al lidiar con datos anuales debido a que las series de tiempo es corta y no presentan patrones estacionales.Dado que nuestros datos son anuales, este modelo se presenta como un posible candidato.

Por su parte @optimalDLM, señala que los DLM de segundo orden son útiles para describir tendencias. Dada la tendencia observada de la serie de defunciones totales sugiere por tanto realizar un modelo  polinomial de segundo orden.

Es oportuno señalar que el desarrollo teórico de estos modelos se llevará a cabo en bitácoras posteriores, ya que se considera prudente primero realizar la implementación de estos (tal como se realizó  el ARIMA$(p,d,q)$) para ver sus alcances para responder la pregunta de investigación. 


