# Bitácora 1

```{r}
#| warning: false
#| echo: false
library(ggplot2)
library(tidyverse)
library(lubridate)
library(kableExtra)
library(dplyr)
library(janitor)
```


En el proyecto se buscará realizar análisis demográfico, específicamente se centrará en el pronóstico de la cantidad de defunciones en Costa Rica.

## Parte 1

### Características generales de la tabla

La tabla de datos proviene del Instituto Nacional de Estadística y Censos (INEC) de Costa Rica y es de acceso público, descargable desde la página web del instituto, como puede consultarse en @INEC_base. Esta base presenta los principales indicadores demográficos anuales de Costa Rica durante el periodo 1950-2020. Incluye en total 18 variables, entre las cuales están el año, la población total al 30 de junio de cada año, desagregado también por sexo, así como la cantidad de defunciones.


### Variables de estudio

**Población de estudio:**   La población de estudio son aquellas personas que vivían en Costa Rica entre los años 1950-2020 y mueren en este periodo.

**Muestra observada:** La muestra observada, son todas aquellas personas que vivían en Costa Rica y al morir son  registrados por el Instituto Nacional de Estadística y Censo.

**Unidad estadística o individuos**: La unidad estadística es el recuento anual de defunciones en Costa Rica. 

**Variables de estudio:** Son un total de 18 variables, las cuales según @INEC_conceptos se tiene: 

**Año:** Esta variable indica el año.

**Total:** Esta variable registra la población total.

**Hombres:** Esta variable registra la población total de hombres.

**Mujeres:** Esta variable se encarga de registar el total de mujeres.

**Nacimientos:** Esta variable registra el total de nacimientos.
 
**Defunciones:** Esta variable registra el total de defunciones.
 
**Defunciones infantiles:** Esta variable registra las defunciones de infantes (niños y niñas).

**Defunciones neonatales:** Esta variable registra las defunciones de recién nacidos, hace referencia a la mortalidad de los nacidos antes de alcanzar los 28 días de edad.

**Defunciones fetales:** Esta variable registra las defunciones de fetos, se refiere a la mortalidad de un bebé antes o durante el parto.
 
**Tasa de crecimiento:** Esta variable registra la tasa de crecimiento de la población costarricense.Se refiere al crecimiento de la población entre dos fechas sin contemplar la migración.
 
**Tasa de natalidad:** Esta variable registra la tasa de nacimientos registrados en la población costarricenses.
 
**Tasa de mortalidad:** Esta variable registra la tasa de muertes en su totalidad.

**Tasa de mortalidad infantil** Esta variable registra la tasa de muertes infantiles.

**Tasa de mortalidad neonatal:** Esta variable registra la tasa de muertes neonatales.

**Tasa de mortalidad fetal:** En esta variable se registra la tasa de muertes fetales.

**Tasa global de fecundidad:** Esta variable registra la tasa de fecundidad global (TGF), la cual indica cantidad de hijos e hijas que en promedio tendría cada mujer al final del periodo fértil, si durante su vida tiene sus hijos e hijas de acuerdo a las tasas de fecundidad por edad observadas en el país y año de interés y, además estas mujeres no están afectadas por la mortalidad desde el nacimiento hasta el final de periodo fértil.

**Tasa bruta de reproducción:** Esta variable hace referencia a el cantidad de hijas que en promedio
tendría cada mujer al final del periodo fértil, si durante su vida tiene sus hijos e hijas de acuerdo a las tasas de fecundidad por edad observadas en el país y año de interés y, además estas mujeres no están afectadas por la mortalidad desde el nacimiento hasta el final de periodo fértil.

**Tasa neta de reproducción:** es el número de hijas que en promedio tendría cada mujer al final del periodo fértil, si durante su vida tiene sus 
hijos e hijas de acuerdo a las tasas de fecundidad por edad observadas en el país y año de interés y, además estas mujeres sí están afectadas por la mortalidad por edad observada en el país y año de interés desde el nacimiento hasta el final de periodo fértil.

### Clasificación de las variables

Todas las variables de la tabla utilizada son numéricas donde cinco identifican cantidades absolutas registradas con respecto a la cantidad de nacimientos, defunciones, etc, y nueve variables son tasas de variabilidad con respecto al año anterior, o como un porcentaje de la población.

## Parte 2

### Pregunta central de investigación

La pregunta formulada es: ¿Cómo se puede realizar un pronóstico de la serie de defunciones totales anuales de Costa Rica?

### Objeto de la investigación

La cantidad de defunciones totales anuales ocurridas en Costa Rica y registradas por el Instituto Nacional de Estadística y Censos del año 1950 hasta el año 2020.

### Conceptos delimitadores de la pregunta de investigación

- Defunciones totales anuales: Según @maccio1985diccionario, la mortalidad o defunción se emplea para expresar la acción de la muerte sobre la población. Esta se mide en valores absolutos y sobre el año calendario.

- Pronóstico: Según @brownlee la realización de predicciones sobre el futuro se denomina extrapolación en el tratamiento estadístico clásico de los datos de las series temporales. Los campos más modernos que se centran en el tema, lo denominan pronóstico de series temporales.El pronóstico consiste en tomar modelos ajustados a datos históricos y utilizarlos para predecir observaciones futuras.

- Serie: De acuerdo a @maccio1985diccionario una series cronológica o crónica se le llama a "la que forman los valores sucesivos que una cierta variable ha tomado en el transcurso del tiempo".

### Principios

@REES2020239 afirma que una de las mayores contribuciones de la demografía ha sido el desarrollo de modelos para la proyección de futuras poblaciones, lo cuál está estrechamente relacionado con la proyección de defunciones. De acuerdo al autor, dos de los modelos más importantes y usados en Demografía cuando a proyección poblacional se refiere, están el de Cohorte-Componente (*The Cohort--Component Model for Projecting the Population*) y el de Proyecciones Probabilísticas (*Probabilistic Projections*).

El modelo de Cohorte-Componente utiliza datos de nacimientos, muertes y migración (a estos factores se les conoce como componentes de cambio) a nivel de cohortes. De acuerdo al Diccionario Demográfico Multilingüe, un cohorte es "conjunto de individuos que han vivido un cierto acontecimiento durante un mismo período" [-@maccio1985diccionario]; y en el marco del modelo puede referirse a grupos de edad. Usualmente, los cohortes están desagregados por sexo [@wilson2021brief].

Por otro lado, el modelo de Proyecciones Probabilísticas, el cual también es establecido en @REES2020239 trata de estimar la población futura a través de los distribuciones de error de ciertos componentes como la tasa de fertilidad. Con estas se pueden proyectar año a año y bajo la combinación de cientos de estos componentes se puede construir escenarios posibles. Cada una de estas distribuciones se puede derivar utilizando datos históricos y a través del uso de modelos de series de tiempo auto-regresivas, o de censos o opiniones experta. Bajo este enfoque se construyen varios escenarios alrededor de una mediana y que se dispersan producto de las distribuciones de incertidumbre pero que al final logran construir un análogo del intervalo de confianza.


